import type { SubscriptionTemplate } from '@/types/subscription';

export const POPULAR_TEMPLATES: SubscriptionTemplate[] = [
  {
    name: 'Netflix',
    icon: '📺',
    color: '#E50914',
    category: 'entertainment',
    defaultPrice: 15.49,
    billingCycle: 'monthly',
  },
  {
    name: 'Spotify',
    icon: '🎵',
    color: '#1DB954',
    category: 'entertainment',
    defaultPrice: 10.99,
    billingCycle: 'monthly',
  },
  {
    name: 'Disney+',
    icon: '🏰',
    color: '#113CCF',
    category: 'entertainment',
    defaultPrice: 13.99,
    billingCycle: 'monthly',
  },
  {
    name: 'HBO Max',
    icon: '🎬',
    color: '#5822B4',
    category: 'entertainment',
    defaultPrice: 15.99,
    billingCycle: 'monthly',
  },
  {
    name: 'Amazon Prime',
    icon: '📦',
    color: '#FF9900',
    category: 'lifestyle',
    defaultPrice: 14.99,
    billingCycle: 'monthly',
  },
  {
    name: 'Apple Music',
    icon: '🎶',
    color: '#FA243C',
    category: 'entertainment',
    defaultPrice: 10.99,
    billingCycle: 'monthly',
  },
  {
    name: 'YouTube Premium',
    icon: '▶️',
    color: '#FF0000',
    category: 'entertainment',
    defaultPrice: 13.99,
    billingCycle: 'monthly',
  },
  {
    name: 'Hulu',
    icon: '📺',
    color: '#1CE783',
    category: 'entertainment',
    defaultPrice: 7.99,
    billingCycle: 'monthly',
  },
  {
    name: 'Adobe Creative Cloud',
    icon: '🎨',
    color: '#FF0000',
    category: 'productivity',
    defaultPrice: 54.99,
    billingCycle: 'monthly',
  },
  {
    name: 'Microsoft 365',
    icon: '📊',
    color: '#0078D4',
    category: 'productivity',
    defaultPrice: 9.99,
    billingCycle: 'monthly',
  },
  {
    name: 'iCloud+',
    icon: '☁️',
    color: '#3693F3',
    category: 'utilities',
    defaultPrice: 2.99,
    billingCycle: 'monthly',
  },
  {
    name: 'Google One',
    icon: '☁️',
    color: '#4285F4',
    category: 'utilities',
    defaultPrice: 2.99,
    billingCycle: 'monthly',
  },
  {
    name: 'Dropbox',
    icon: '📁',
    color: '#0061FF',
    category: 'utilities',
    defaultPrice: 11.99,
    billingCycle: 'monthly',
  },
  {
    name: 'Notion',
    icon: '📝',
    color: '#000000',
    category: 'productivity',
    defaultPrice: 8.00,
    billingCycle: 'monthly',
  },
  {
    name: 'Slack',
    icon: '💬',
    color: '#4A154B',
    category: 'productivity',
    defaultPrice: 8.75,
    billingCycle: 'monthly',
  },
  {
    name: 'Xbox Game Pass',
    icon: '🎮',
    color: '#107C10',
    category: 'entertainment',
    defaultPrice: 16.99,
    billingCycle: 'monthly',
  },
  {
    name: 'PlayStation Plus',
    icon: '🎮',
    color: '#003791',
    category: 'entertainment',
    defaultPrice: 17.99,
    billingCycle: 'monthly',
  },
  {
    name: 'Nintendo Switch Online',
    icon: '🎮',
    color: '#E60012',
    category: 'entertainment',
    defaultPrice: 3.99,
    billingCycle: 'monthly',
  },
  {
    name: 'Gym Membership',
    icon: '💪',
    color: '#FF6B6B',
    category: 'health',
    defaultPrice: 30.00,
    billingCycle: 'monthly',
  },
  {
    name: 'Headspace',
    icon: '🧘',
    color: '#F47D31',
    category: 'health',
    defaultPrice: 12.99,
    billingCycle: 'monthly',
  },
  {
    name: 'Duolingo Plus',
    icon: '🦉',
    color: '#58CC02',
    category: 'education',
    defaultPrice: 6.99,
    billingCycle: 'monthly',
  },
  {
    name: 'LinkedIn Premium',
    icon: '💼',
    color: '#0A66C2',
    category: 'productivity',
    defaultPrice: 29.99,
    billingCycle: 'monthly',
  },
  {
    name: 'The New York Times',
    icon: '📰',
    color: '#000000',
    category: 'news',
    defaultPrice: 4.25,
    billingCycle: 'weekly',
  },
  {
    name: 'Audible',
    icon: '🎧',
    color: '#FF9900',
    category: 'entertainment',
    defaultPrice: 14.95,
    billingCycle: 'monthly',
  },
];

export const CATEGORY_COLORS: Record<string, string> = {
  entertainment: '#FF7A5C',
  productivity: '#4A90D9',
  lifestyle: '#9B59B6',
  utilities: '#34495E',
  news: '#2C3E50',
  education: '#27AE60',
  finance: '#F39C12',
  health: '#E74C3C',
  other: '#95A5A6',
};
